name: Publish Snapshot Release

on:
  workflow_dispatch: # Trigger manually

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Download previously uploaded artifacts
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts # Download artifacts to 'artifacts' folder

    # Step 3: Zip artifacts (optional, if needed for release)
    - name: Zip artifacts
      run: |
        #zip -r snapshot-artifacts.zip artifacts
        ls artifacts

    # Step 4: Create or update a release
    #- name: Create Snapshot Release
    #  uses: softprops/action-gh-release@v1
    #  with:
    #    files: |
    #      snapshot-artifacts.zip # Upload the zipped file to release
    #    tag_name: "${{ github.event.inputs.release_name }}"
    #    release_name: "${{ github.event.inputs.release_name }}"
    #    draft: false
    #    prerelease: true
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

